#: bears/tests/misc/LineCountBearTest.py:21
#: bears/tests/misc/LineCountBearTest.py:29 bears/misc/LineCountBear.py:14
#, python-brace-format
msgid "This file has {count} lines."
msgstr ""

#: bears/misc/KeywordBear.py:36
msgid "Line contains the following keywords:"
msgstr ""

#: bears/misc/LineLengthBear.py:27
msgid "Line is longer than allowed."
msgstr ""

#: bears/spacing/SpaceConsistencyBear.py:42
msgid "Line contains spacing inconsistencies."
msgstr ""

#. pragma: no cover
#: coalib/processes/BearRunner.py:120
msgid ""
"An unknown error occurred while running local bears for the file {}. "
"Skipping file..."
msgstr ""

#. pragma: no cover
#: coalib/processes/BearRunner.py:140
msgid ""
"An unknown error occurred while running global bear {}. Skipping bear..."
msgstr ""

#: coalib/processes/BearRunner.py:154
msgid "An internal error occurred."
msgstr ""

#: coalib/processes/BearRunner.py:155
msgid "The given file through the queue is not in the file dictionary."
msgstr ""

#: coalib/processes/BearRunner.py:170 coalib/processes/BearRunner.py:180
msgid "A given local bear ({}) is not valid. Leaving it out..."
msgstr ""

#: coalib/output/Interactor.py:38
msgid ""
"One of the results can not be printed since it is not a valid derivative of "
"the coala result class."
msgstr ""

#: coalib/output/printers/LOG_LEVEL.py:4
#: coalib/output/printers/LogPrinter.py:29
#: coalib/tests/processes/communication/LogMessageTest.py:35
#: coalib/tests/output/printers/LogPrinterTest.py:39
msgid "DEBUG"
msgstr ""

#: coalib/output/printers/LOG_LEVEL.py:4
#: coalib/output/printers/LogPrinter.py:30
#: coalib/tests/processes/communication/LogMessageTest.py:33
#: coalib/tests/output/printers/LogPrinterTest.py:44
msgid "WARNING"
msgstr ""

#: coalib/output/printers/LOG_LEVEL.py:4
#: coalib/output/printers/LogPrinter.py:31
#: coalib/tests/processes/communication/LogMessageTest.py:31
#: coalib/tests/processes/communication/LogMessageTest.py:37
#: coalib/tests/output/printers/LogPrinterTest.py:32
#: coalib/tests/output/printers/LogPrinterTest.py:35
#: coalib/tests/output/printers/LogPrinterTest.py:47
#: coalib/tests/output/printers/LogPrinterTest.py:50
msgid "ERROR"
msgstr ""

#: coalib/output/printers/LogPrinter.py:50
#: coalib/tests/output/printers/LogPrinterTest.py:51
msgid "Exception was:"
msgstr ""

#. pragma: no cover
#: coalib/output/printers/EspeakPrinter.py:19
msgid ""
"eSpeak doesn't seem to be installed. You cannot use the voice output feature "
"without eSpeak. It can be downloaded from http://espeak.sourceforge.net/ or "
"installed via your usual package repositories."
msgstr ""

#. pragma: no cover
#: coalib/output/printers/EspeakPrinter.py:24
msgid "Failed to execute eSpeak. An unknown error occurred."
msgstr ""

#: coalib/output/ConsoleInteractor.py:9
msgid "Please enter a value for the setting \"{}\" ({}) needed by {}: "
msgstr ""

#: coalib/output/ConsoleInteractor.py:10
msgid ""
"The line belonging to the following result cannot be printed because it "
"refers to a line that doesn't seem to exist in the given file."
msgstr ""

#: coalib/output/ConsoleInteractor.py:12
msgid "Project wide:"
msgstr ""

#: coalib/output/ConsoleInteractor.py:42
msgid "One of the given settings ({}) are not properly described."
msgstr ""

#. Translators: this is the and that connects the last two items of an enumeration (1st, 2nd AND 3rd)
#: coalib/output/ConsoleInteractor.py:50
#: coalib/tests/output/ConsoleInteractorTest.py:49
#: coalib/tests/output/ConsoleInteractorTest.py:57
msgid " and "
msgstr ""

#: coalib/output/ConsoleInteractor.py:67
msgid "The following options are applicable to this result:"
msgstr ""

#: coalib/output/ConsoleInteractor.py:81
msgid "No action."
msgstr ""

#: coalib/output/ConsoleInteractor.py:84
msgid "Please enter the number of the action you want to execute."
msgstr ""

#: coalib/output/ConsoleInteractor.py:90
msgid "Please enter a valid number."
msgstr ""

#: coalib/output/ConsoleInteractor.py:102
msgid "Please enter a value for the parameter '{}' ({}):"
msgstr ""

#: coalib/output/ConsoleInteractor.py:145
msgid ""
"A result ({}) cannot be printed because it refers to a file that doesn't "
"seem to exist."
msgstr ""

#: coalib/collecting/Collectors.py:85
msgid "unable to import bears from {}"
msgstr ""

#: coalib/settings/SectionFiller.py:37
msgid "One of the given bears ({}) has no attribute get_non_optional_settings."
msgstr ""

#: coalib/settings/FunctionMetadata.py:8
msgid "No description given."
msgstr ""

#: coalib/settings/FunctionMetadata.py:9
msgid "Optional, defaults to '{}'."
msgstr ""

#: coalib/settings/Section.py:59
msgid ""
"Failed to instantiate the logging method '{}'. Falling back to console "
"output."
msgstr ""

#: coalib/settings/SectionManager.py:63
msgid ""
"The global default coafile for the settings was not found. It seems your "
"installation is broken."
msgstr ""

#. Do not change this translation without changing it in the code also!
#: coalib/tests/misc/i18nTest.py:36 coalib/tests/misc/i18nTest.py:41
#: coalib/tests/bears/BearTest.py:26 coalib/tests/bears/BearTest.py:66
msgid "A string to test translations."
msgstr ""

#: coalib/tests/misc/i18nTest.py:47
msgid "A not directly translated test string."
msgstr ""

#: coalib/tests/misc/StringConverterTest.py:53
#: coalib/misc/StringConstants.py:19
msgid "yeah"
msgstr ""

#: coalib/tests/misc/StringConverterTest.py:57
#: coalib/misc/StringConstants.py:28
msgid "nope"
msgstr ""

#: coalib/tests/bears/BearTest.py:63 coalib/tests/bears/BearTest.py:73
#: coalib/bears/Bear.py:86
msgid "Setting up bear {}..."
msgstr ""

#: coalib/tests/bears/BearTest.py:65 coalib/tests/bears/BearTest.py:74
#: coalib/bears/Bear.py:88
msgid "Running bear {}..."
msgstr ""

#: coalib/tests/bears/BearTest.py:67 coalib/tests/bears/BearTest.py:75
#: coalib/bears/Bear.py:102
msgid "Tearing down bear {}..."
msgstr ""

#: coalib/tests/bears/BearTest.py:76 coalib/bears/Bear.py:93
#: coalib/bears/Bear.py:108
msgid "Bear {} failed to run"
msgstr ""

#: coalib/tests/results/RESULT_SEVERITYTest.py:11
#: coalib/results/RESULT_SEVERITY.py:5
msgid "INFO"
msgstr ""

#: coalib/tests/results/RESULT_SEVERITYTest.py:12
#: coalib/results/RESULT_SEVERITY.py:5
msgid "NORMAL"
msgstr ""

#: coalib/tests/results/RESULT_SEVERITYTest.py:13
#: coalib/results/RESULT_SEVERITY.py:5
msgid "MAJOR"
msgstr ""

#: coalib/misc/StringConstants.py:8
msgid ""
"This is a bug. We are sorry for the inconvenience. Please contact the "
"developers for assistance."
msgstr ""

#: coalib/misc/StringConstants.py:11
msgid "{} is not accessible and will be ignored!"
msgstr ""

#: coalib/misc/StringConstants.py:19
msgid "on"
msgstr ""

#: coalib/misc/StringConstants.py:19
msgid "y"
msgstr ""

#: coalib/misc/StringConstants.py:19
msgid "yes"
msgstr ""

#: coalib/misc/StringConstants.py:19
msgid "sure"
msgstr ""

#: coalib/misc/StringConstants.py:19
msgid "true"
msgstr ""

#: coalib/misc/StringConstants.py:20
msgid "definitely"
msgstr ""

#: coalib/misc/StringConstants.py:20
msgid "yup"
msgstr ""

#: coalib/misc/StringConstants.py:20
msgid "right"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "off"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "n"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "no"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "nah"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "false"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "wrong"
msgstr ""

#: coalib/bears/Bear.py:94
#, python-brace-format
msgid ""
"The bear {bear} raised an exception of type {exception}. If you are the "
"writer of this bear, please catch all exceptions. If not and this error "
"annoys you, you might want to get in contact with the writer of this bear.\n"
"\n"
"Here is your traceback:\n"
"\n"
"{traceback}\n"
msgstr ""

#: coalib/bears/Bear.py:109
msgid ""
"set_up() or tear_down() throwed an exception for bear {}.\n"
"Exception: {}\n"
"Traceback:\n"
"{}"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:13
msgid "Sections to be executed exclusively."
msgstr ""

#: coalib/parsing/DefaultArgParser.py:18
msgid "Files that should be checked"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:23
msgid "Names of bears to use"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:24
msgid "Additional directories where bears may lie"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:30
msgid "Type of logging (console or any filename)"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:36
msgid "Enum('ERR','WARN','DEBUG') to set level of log output"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:43
msgid "Type of output (console or any filename)"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:53
msgid "Configuration file to be used"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:54
msgid "Filename of file to be saved to, defaults to config file"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:61
msgid "Arbitrary settings in the form of section.key=value"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:67
msgid "Number of processes to be allowed to run at once"
msgstr ""

#: coalib/parsing/DefaultArgParser.py:74
msgid "Enum('YES','NO','ASK') to set whether to apply changes"
msgstr ""

#: coala:50
msgid "Program terminated by user."
msgstr ""

#: coala:55
msgid "An unknown error occurred."
msgstr ""

#: coala:58
#, python-brace-format
msgid ""
"During execution of coala an exception of type {exception} was raised. This "
"should never happen. When asked for, the following information may help "
"investigating:"
msgstr ""
