msgid ""
msgstr ""
"Project-Id-Version: coala 0.2\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: Lasse Schuirmann <lasse.schuirmann@gmail.com>\n"
"Language-Team: \n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.7.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: bears/misc/LineLengthBear.py:27
msgid "Line is longer than allowed."
msgstr "Zeile ist länger als erlaubt."

#: bears/misc/KeywordBear.py:36
msgid "Line contains the following keywords:"
msgstr "Zeile enthält die folgenden Schlüsselwörter:"

#: bears/spacing/SpaceConsistencyBear.py:42
msgid "Line contains spacing inconsistencies."
msgstr "Zeile enthält uneinheitliche Leerzeichen."

#: coalib/processes/communication/LogMessage.py:16
#: coalib/tests/processes/communication/LogMessageTest.py:35
#: coalib/tests/output/printers/LogPrinterTest.py:39
#: coalib/output/printers/LogPrinter.py:29
msgid "DEBUG"
msgstr "DEBUG"

#: coalib/processes/communication/LogMessage.py:17
#: coalib/tests/processes/communication/LogMessageTest.py:33
#: coalib/tests/output/printers/LogPrinterTest.py:44
#: coalib/output/printers/LogPrinter.py:30
msgid "WARNING"
msgstr "WARNUNG"

#: coalib/processes/communication/LogMessage.py:18
#: coalib/tests/processes/communication/LogMessageTest.py:31
#: coalib/tests/processes/communication/LogMessageTest.py:37
#: coalib/tests/output/printers/LogPrinterTest.py:32
#: coalib/tests/output/printers/LogPrinterTest.py:35
#: coalib/tests/output/printers/LogPrinterTest.py:47
#: coalib/tests/output/printers/LogPrinterTest.py:50
#: coalib/output/printers/LogPrinter.py:31
msgid "ERROR"
msgstr "FEHLER"

#. pragma: no cover
#: coalib/processes/BearRunner.py:120
msgid ""
"An unknown error occurred while running local bears for the file {}. "
"Skipping file..."
msgstr ""
"Beim Ausführen des lokalen Bären für die Datei {} ist ein unbekannter Fehler "
"aufgetreten. Die Datei wird übersprungen..."

#. pragma: no cover
#: coalib/processes/BearRunner.py:140
msgid ""
"An unknown error occurred while running global bear {}. Skipping bear..."
msgstr ""
"Ein unbekannter Fehler ist beim Ausführen des globalen Bären {} aufgetreten. "
"Der Bär wird übersprungen..."

#: coalib/processes/BearRunner.py:154
msgid "An internal error occurred."
msgstr "Ein interner Fehler ist aufgetreten."

#: coalib/processes/BearRunner.py:155
msgid "The given file through the queue is not in the file dictionary."
msgstr ""
"Die durch die Warteschlange übergebene Datei befindet sich nicht in dem "
"Dateiordner."

#: coalib/processes/BearRunner.py:170 coalib/processes/BearRunner.py:180
msgid "A given local bear ({}) is not valid. Leaving it out..."
msgstr "Der lokale Bär ({}) ist nicht korrekt.  Er wird ausgelassen..."

#: coalib/misc/StringConstants.py:8
msgid ""
"This is a bug. We are sorry for the inconvenience. Please contact the "
"developers for assistance."
msgstr ""
"Dies ist ein Fehler. Wir entschuldigen uns für die Unannehmlichkeiten. Bitte "
"kontaktieren Sie die Entwickler für Unterstützung."

#: coalib/misc/StringConstants.py:11
msgid "{} is not accessible and will be ignored!"
msgstr "Auf {} konnte nicht zugegriffen werden. Es wird ignoriert!"

#: coalib/misc/StringConstants.py:19
msgid "on"
msgstr "an"

#: coalib/misc/StringConstants.py:19
msgid "y"
msgstr "j"

#: coalib/misc/StringConstants.py:19
msgid "yes"
msgstr "ja"

#: coalib/misc/StringConstants.py:19
#: coalib/tests/misc/StringConverterTest.py:53
msgid "yeah"
msgstr "klar"

#: coalib/misc/StringConstants.py:19
msgid "sure"
msgstr "sicher"

#: coalib/misc/StringConstants.py:19
msgid "true"
msgstr "wahr"

#: coalib/misc/StringConstants.py:20
msgid "definitely"
msgstr "definitiv"

#: coalib/misc/StringConstants.py:20
msgid "yup"
msgstr "jup"

#: coalib/misc/StringConstants.py:20
msgid "right"
msgstr "richtig"

#: coalib/misc/StringConstants.py:28
msgid "off"
msgstr "aus"

#: coalib/misc/StringConstants.py:28
msgid "n"
msgstr "n"

#: coalib/misc/StringConstants.py:28
msgid "no"
msgstr "nein"

#: coalib/misc/StringConstants.py:28
#: coalib/tests/misc/StringConverterTest.py:57
msgid "nope"
msgstr "ne"

#: coalib/misc/StringConstants.py:28
msgid "nah"
msgstr "neh"

#: coalib/misc/StringConstants.py:28
msgid "false"
msgstr "falsch"

#: coalib/misc/StringConstants.py:28
msgid "wrong"
msgstr "unwahr"

#: coalib/bears/Bear.py:86 coalib/tests/bears/BearTest.py:63
#: coalib/tests/bears/BearTest.py:73
msgid "Setting up bear {}..."
msgstr "Bereite Bär {} vor..."

#: coalib/bears/Bear.py:88 coalib/tests/bears/BearTest.py:65
#: coalib/tests/bears/BearTest.py:74
msgid "Running bear {}..."
msgstr "Führe Bär {} aus..."

#: coalib/bears/Bear.py:93 coalib/bears/Bear.py:108
#: coalib/tests/bears/BearTest.py:76
msgid "Bear {} failed to run"
msgstr "Der Bär {} konnte nicht ausgeführt werden"

#: coalib/bears/Bear.py:94
#, python-brace-format
msgid ""
"The bear {bear} raised an exception of type {exception}. If you are the "
"writer of this bear, please catch all exceptions. If not and this error "
"annoys you, you might want to get in contact with the writer of this bear.\n"
"\n"
"Here is your traceback:\n"
"\n"
"{traceback}\n"
msgstr ""
"Der Bär {bear} hat eine Ausnahme vom Typ {exception} geworfen. Wenn Sie der "
"Entwickler dieses Bären sind, fangen Sie bitte alle Ausnahmen ab. Wenn Sie "
"es nicht sind und dieser Fehler Sie nervt, kontaktieren Sie bitte den "
"Entwickler dieses Bären.\n"
"\n"
"Hier ist Ihre Rückverfolgung:\n"
"\n"
"{traceback}\n"

#: coalib/bears/Bear.py:102 coalib/tests/bears/BearTest.py:67
#: coalib/tests/bears/BearTest.py:75
msgid "Tearing down bear {}..."
msgstr "Beende Bär {}..."

#: coalib/bears/Bear.py:109
msgid ""
"set_up() or tear_down() throwed an exception for bear {}.\n"
"Exception: {}\n"
"Traceback:\n"
"{}"
msgstr ""
"set_up() oder tear_down() hat eine Ausnahme beim Bären {} geworfen.\n"
"Ausnahme: {}\n"
"Rückverfolgung:\n"
"{}"

#: coalib/collecting/BearCollector.py:111
#: coalib/collecting/FileCollector.py:110
#, python-brace-format
msgid ""
"One of the given regexes ('{regex}') was not valid and will be ignored. The "
"error was '{error}'."
msgstr ""
"Einer der übergebenen regulären Ausdrücke ('{regex}') ist ungültig und wird "
"ignoriert. Der Fehler war '{error}'."

#: coalib/results/RESULT_SEVERITY.py:11
#: coalib/tests/results/RESULT_SEVERITYTest.py:11
msgid "INFO"
msgstr "INFO"

#: coalib/results/RESULT_SEVERITY.py:12 coalib/results/RESULT_SEVERITY.py:13
#: coalib/tests/results/RESULT_SEVERITYTest.py:12
msgid "NORMAL"
msgstr "NORMAL"

#: coalib/results/RESULT_SEVERITY.py:13
#: coalib/tests/results/RESULT_SEVERITYTest.py:13
msgid "MAJOR"
msgstr "WICHTIG"

#. Do not change this translation without changing it in the code also!
#: coalib/tests/misc/i18nTest.py:36 coalib/tests/misc/i18nTest.py:40
#: coalib/tests/bears/BearTest.py:26 coalib/tests/bears/BearTest.py:66
msgid "A string to test translations."
msgstr "Eine Zeichenkette um Übersetzungen zu testen."

#. Translators: this is the and that connects the last two items of an enumeration (1st, 2nd AND 3rd)
#: coalib/tests/output/ConsoleInteractorTest.py:41
#: coalib/tests/output/ConsoleInteractorTest.py:49
#: coalib/output/ConsoleInteractor.py:52
msgid " and "
msgstr " und "

#: coalib/tests/output/printers/LogPrinterTest.py:51
#: coalib/output/printers/LogPrinter.py:50
msgid "Exception was:"
msgstr "Die Ausnahme war:"

#: coalib/settings/SectionFiller.py:37
msgid "One of the given bears ({}) has no attribute get_non_optional_settings."
msgstr ""
"Einem der gegebenen Bären ({}) fehlt das Attribut get_non_optional_settings."

#: coalib/settings/Section.py:57
msgid ""
"Failed to instantiate the logging method '{}'. Falling back to console "
"output."
msgstr ""
"Fehler beim instanziieren der Protokollmethode '{}'. Schalte auf "
"Konsolenausgabe zurück."

#: coalib/settings/FunctionMetadata.py:8
msgid "No description given."
msgstr "Keine Beschreibung vorhanden."

#: coalib/settings/FunctionMetadata.py:9
msgid "Optional, defaults to '{}'."
msgstr "Optional, standardmäßig '{}'."

#: coalib/settings/SectionManager.py:57
msgid ""
"The global default coafile for the settings was not found. It seems your "
"installation is broken."
msgstr ""
"Das globale standard coafile für die Einstellungen wurde nicht gefunden. Es "
"scheint, als ob Ihre Installation kaputt ist."

#: coalib/parsing/DefaultArgParser.py:9
msgid "Files that should be checked"
msgstr "Dateien die überprüft werden sollen"

#: coalib/parsing/DefaultArgParser.py:11
msgid "Regex for additional filenames (only the tail of the whole path)"
msgstr ""
"Regulärer Ausdruck für weitere Dateinamen (nur das Ende des gesamten Pfades)"

#: coalib/parsing/DefaultArgParser.py:13
msgid ""
"Directories where files may lie that will be checked, excluding sub "
"directories"
msgstr ""
"Ordner in denen die zu überprüfenden Dateien liegen, ohne Unterverzeichnisse"

#: coalib/parsing/DefaultArgParser.py:16
msgid ""
"Directories where files may lie that will be checked, including sub "
"directories"
msgstr ""
"Ordner in denen die zu überprüfenden Dateien liegen, mit Unterverzeichnissen"

#: coalib/parsing/DefaultArgParser.py:19
msgid "Directories that should be ignored"
msgstr "Ordner, welche ignoriert werden sollen"

#: coalib/parsing/DefaultArgParser.py:21
msgid "Directories where bears may lie, excluding subdirectories"
msgstr "Ordner in denen Bären liegen, ohne Unterverzeichnisse"

#: coalib/parsing/DefaultArgParser.py:23
msgid "Directories where bears may lie, including subdirectories"
msgstr "Ordner in denen Bären liegen, mit Unterverzeichnissen"

#: coalib/parsing/DefaultArgParser.py:25
msgid "Directories to ignore when searching for bears"
msgstr "Ordner, welche bei der Suche nach Bären ignoriert werden sollen"

#: coalib/parsing/DefaultArgParser.py:27
msgid "Names of bears to use"
msgstr "Namen der zu benutzenden Bären"

#: coalib/parsing/DefaultArgParser.py:29
msgid "Regular expression for bears to use"
msgstr "Regulärer Ausdruck für die zu benutzenden Bären"

#: coalib/parsing/DefaultArgParser.py:31
msgid "Type of logging (console or any filename)"
msgstr "Art der Protokollierung (console oder ein Dateiname)"

#: coalib/parsing/DefaultArgParser.py:34
msgid "Enum('ERR','WARN','DEBUG') to set level of log output"
msgstr "Setzt die Art der Prokollierung fest, Enum('ERR','WARN','DEBUG')"

#: coalib/parsing/DefaultArgParser.py:36
msgid "Type of output (console or any filename)"
msgstr "Art der Ausgabe (console oder ein Dateiname)"

#: coalib/parsing/DefaultArgParser.py:38
msgid "Configuration file to be used"
msgstr "Zu benutzende Konfigurationsdatei"

#: coalib/parsing/DefaultArgParser.py:40
msgid "Filename of file to be saved to, defaults to config file"
msgstr ""
"Datei in die gespeichert werden soll, Standard ist die Konfigurationsdatei"

#: coalib/parsing/DefaultArgParser.py:42
msgid "Arbitrary settings in the form of section.key=value"
msgstr "Beliebige Einstellung in der Form section.key=value"

#: coalib/parsing/DefaultArgParser.py:44
msgid "Number of processes to be allowed to run at once"
msgstr "Anzahl an Prozessen, welche gleichzeitig ausgeführt werden dürfen"

#: coalib/parsing/DefaultArgParser.py:46
msgid "Enum('YES','NO','ASK') to set whether to apply changes"
msgstr "Legt fest ob Änderungen angewandt werden, Enum('YES','NO','ASK')"

#: coalib/output/ConsoleInteractor.py:11
msgid "Please enter a value for the setting \"{}\" ({}) needed by {}: "
msgstr ""
"Bitte geben Sie einen Wert für die Einstellung \"{}\" ({}) ein, welche von "
"{} benötigt wird: "

#: coalib/output/ConsoleInteractor.py:12
msgid ""
"A the line belonging to the following result cannot be printed because it "
"refers to a line that doesn't seem to exist in the given file."
msgstr ""

#: coalib/output/ConsoleInteractor.py:14
msgid "Project wide:"
msgstr "Projektweit:"

#: coalib/output/ConsoleInteractor.py:44
msgid "One of the given settings ({}) are not properly described."
msgstr ""
"Eine der übergebenen Einstellungen ({}) wurde nicht ordentlich beschrieben."

#: coalib/output/ConsoleInteractor.py:69
msgid "The following options are applicable to this result:"
msgstr "Die folgenden Optionen sind für dieses Ergebnis zutreffend:"

#: coalib/output/ConsoleInteractor.py:83
msgid "No action."
msgstr "Keine Aktion."

#: coalib/output/ConsoleInteractor.py:86
msgid "Please enter the number of the action you want to execute."
msgstr ""
"Bitte geben Sie die Nummer der Aktion ein, welche Sie ausführen möchten."

#: coalib/output/ConsoleInteractor.py:92
msgid "Please enter a valid number."
msgstr "Bitte geben Sie eine gültige Zahl ein."

#: coalib/output/ConsoleInteractor.py:104
msgid "Please enter a value for the parameter '{}' ({}):"
msgstr "Bitte geben Sie einen Wert für den Parameter '{}' ({}) ein:"

#: coalib/output/ConsoleInteractor.py:147
msgid ""
"A result ({}) cannot be printed because it refers to a file that doesn't "
"seem to exist."
msgstr ""
"Das Ergebnis ({}) kann nicht ausgegeben werden, da es auf eine Datei "
"verweist, welche nicht zu existieren scheint."

#. pragma: no cover
#: coalib/output/printers/EspeakPrinter.py:19
msgid ""
"Espeak doesn't seem to be installed. You cannot use the voice output feature "
"without espeak. It can be downloaded from http://espeak.sourceforge.net/ or "
"installed via your usual package repositories."
msgstr ""
"eSpeak scheint nicht installiert zu sein. Sie können die "
"Sprachausgabefunktion nicht nutzen ohne eSpeak. eSpeak kann von http://"
"espeak.sourceforge.net/ heruntergeladen oder über Ihre Paketrepositorys "
"installiert werden."

#. pragma: no cover
#: coalib/output/printers/EspeakPrinter.py:24
msgid "Failed to execute espeak. An unknown error occurred."
msgstr ""
"eSpeak konnte nicht ausgeführt werden. Ein unbekannter Fehler ist "
"aufgetreten."

#: coalib/output/Interactor.py:38
msgid ""
"One of the results can not be printed since it is not a valid derivative of "
"the coala result class."
msgstr ""
"Eines der Ergebnisse kann nicht ausgegeben werden, da es keine korrekte "
"Ableitung der coala result Klasse ist."

#: coala:42
msgid "Program terminated by user."
msgstr "Das Programm wurde durch den Benutzer beendet."

#: coala:47
msgid "An unknown error occurred."
msgstr "Ein unbekannter Fehler ist aufgetreten."

#: coala:48
#, python-brace-format
msgid ""
"During execution of coala an exception of type {exception} was raised. This "
"should never happen. When asked for, the following information may help "
"investigating:"
msgstr ""
"Während der Ausführung von coala ist eine Ausnahme vom Typ {exception} "
"aufgetreten. Das sollte niemals passieren. Wenn Sie danach gefragt werden, "
"helfen die folgenden Informationen womöglich bei der Untersuchung der "
"Ursache:"

#~ msgid ""
#~ "This is a bug. We are sorry for the inconvenience. Please contact the "
#~ "developers if this happens more than once."
#~ msgstr ""
#~ "Dies ist ein Bug. Wir möchten uns für die Unannehmlichkeiten "
#~ "entschuldigen. Wenn dies mehr als einmal passiert, kontaktieren Sie bitte "
#~ "die Entwickler."

#~ msgid ""
#~ "Failed reading file. Please make sure to provide a file that is existent "
#~ "and you have the permission to read it."
#~ msgstr ""
#~ "Das Lesen der Datei ist gescheitert. Bitte stellen Sie sicher dass die "
#~ "Datei existiert und Leserechte vorhanden sind."

#~ msgid ""
#~ "Unknown failure in worker process.\n"
#~ "Exception: {}\n"
#~ "Traceback:\n"
#~ "{}"
#~ msgstr ""
#~ "Unbekannter Fehler im Arbeitsprozess.\n"
#~ "Exception: {}\n"
#~ "Traceback:\n"
#~ "{}"

#~ msgid "An unknown failure occurred and an analyzer run is aborted."
#~ msgstr ""
#~ "Ein Unbekannter Fehler ist aufgetreten und eine Ausführung einer "
#~ "Analyseroutine wurde abgebrochen."

#~ msgid "defaults has to be a Settings object or None."
#~ msgstr "defaults muss ein Settings Objekt oder None sein."

#~ msgid "defaults may not be self for non-recursivity."
#~ msgstr "defaults darf nicht self sein um Rekursivität zu vermeiden."

#~ msgid "Empty keys are invalid."
#~ msgstr "Leere Schlüssel sind ungültig."

#~ msgid "Required index is unavailable."
#~ msgstr "Der angeforderte Index ist nicht verfügbar."

#~ msgid " yeah "
#~ msgstr "jep"

#~ msgid " nope "
#~ msgstr "nö"
